CREATE SCHEMA RRZ0AUTH;

USE RRZ0AUTH;

CREATE TABLE ADDRESS (  
address_id INT AUTO_INCREMENT  PRIMARY KEY,  
address_line1 VARCHAR(50) NOT NULL,
address_line2 VARCHAR(50) NOT NULL,
city VARCHAR(10) NOT NULL,
province VARCHAR(2) NOT NULL,
country VARCHAR(2) NOT NULL,
zipcode VARCHAR(6) NOT NULL
); 